services:
  devcontainer:
    image: devcontainer
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DEV_REPO_URL: ${DEV_REPO_URL}
    environment:
      DISCORD_API_KEY: ${DISCORD_API_KEY}
      IMGUR_API_KEY: ${IMGUR_API_KEY}
      IMGUR_API_SECRET: ${IMGUR_API_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TENOR_API_KEY: ${TENOR_API_KEY}
      ADMIN_USER_ID: ${ADMIN_USER_ID}
      ADDITIONAL_SYNC_PERMISSIONS: ${ADDITIONAL_SYNC_PERMISSIONS}
      ERROR_LOG_CHANNEL_ID: ${ERROR_LOG_CHANNEL_ID}
    volumes:
      - ./../database.sqlite:/app/Crunchy-Bot/database.sqlite
    tty: true
    command: sleep infinity
